image: moodlehq/moodle-php-apache:7.0

services:
 - mysql:latest

cache:
 paths:
 - $HOME/.composer/cache

variables:
 MOODLE_BRANCH: "master"
 DB: "mysqli"
 MYSQL_ROOT_PASSWORD: "superrootpass"
 TRAVIS_BUILD_DIR: "$CI_PROJECT_DIR"

before_script:
 - apt update && apt install git-core mysql-client npm -y
 - cd $CI_PROJECT_DIR/..
 - curl -sS https://getcomposer.org/installer | php
 - mv composer.phar /usr/local/bin/composer
 - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
 - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
 - chmod u+x ci/bin/moodle-plugin-ci
 - chmod u+x ci/bin/*
 - umask u+x
 - moodle-plugin-ci install --db-user=root --db-pass=superrootpass --db-host=mysql -vvv

job1:
 script:
 - moodle-plugin-ci phplint ; moodle-plugin-ci phpcpd ; moodle-plugin-ci phpmd ; moodle-plugin-ci codechecker ; moodle-plugin-ci csslint ; moodle-plugin-ci shifter ; moodle-plugin-ci jshint ; moodle-plugin-ci validate ; moodle-plugin-ci phpunit ; moodle-plugin-ci behat
